-- 按箱管理所需字段。请在 Supabase SQL Editor 中执行一次。
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS brand TEXT;
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS lot TEXT;
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS dc TEXT;
ALTER TABLE inventory ADD COLUMN IF NOT EXISTS origin TEXT;

ALTER TABLE sales ADD COLUMN IF NOT EXISTS brand TEXT;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS lot TEXT;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS dc TEXT;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS origin TEXT;

ALTER TABLE summary ADD COLUMN IF NOT EXISTS brand TEXT;
ALTER TABLE summary ADD COLUMN IF NOT EXISTS lot TEXT;
ALTER TABLE summary ADD COLUMN IF NOT EXISTS dc TEXT;
ALTER TABLE summary ADD COLUMN IF NOT EXISTS origin TEXT;
